name       : openbox
version    : 3.6.1
release    : 3
source     :
    - http://openbox.org/dist/openbox/openbox-3.6.1.tar.xz : abe75855cc5616554ffd47134ad15291fe37ebbebf1a80b69cbde9d670f0e26d
license    : GPL-2.0-or-later
component  : desktop
summary    : lightweight window manager
description: |
    Openbox is a highly configurable, next generation window manager with extensive standards support.
builddeps  :
    - pkgconfig(pango)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
rundeps    :
    - pyxdg
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -m 00064 $pkgfiles/openbox.desktop $installdir/usr/share/xsessions/openbox.desktop
    install -D -m 00064 $pkgfiles/menu.xml %installdir/etc/xdg/openbox/menu.xml
    install -D -m 00755 $pkgfiles/openbox-dbus $installdir/usr/bin/openbox-dbus
