name       : openbox
version    : 3.6.1
release    : 1
source     :
    - http://openbox.org/dist/openbox/openbox-3.6.1.tar.gz : 8b4ac0760018c77c0044fab06a4f0c510ba87eae934d9983b10878483bde7ef7
license    : GPL-2.0 
component  : desktop
summary    : lightweight window manager
description: |
    Openbox is a highly configurable, next generation window manager with extensive standards support.
builddeps  :
    - pkgconfig(pango)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
rundeps :
    - pyxdg
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -m0064 $pkgfiles/openbox.desktop $installdir/usr/share/xsessions/openbox.desktop
    install -Dm0064 $pkgfiles/menu.xml %installdir/etc/xdg/openbox/menu.xml
